"""add updated_at to conversations

Revision ID: b6dcec03b855
Revises: 3fc4559bf74f
Create Date: 2025-12-13 22:33:55.243748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6dcec03b855'
down_revision: Union[str, Sequence[str], None] = '3fc4559bf74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('user_id',
                   existing_type=sa.CHAR(length=36),
                   type_=sa.UUID(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.UUID(),
                   type_=sa.CHAR(length=36),
                   existing_nullable=True)
        batch_op.drop_column('updated_at')
    # ### end Alembic commands ###
