"""add users table and update conversations

Revision ID: eb4eedf542c5
Revises: 1c5381cea25c
Create Date: 2025-12-13 20:03:17.320563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'eb4eedf542c5'
down_revision: Union[str, Sequence[str], None] = '1c5381cea25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                existing_type=sa.VARCHAR(),
                type_=fastapi_users_db_sqlalchemy.generics.GUID(),
                existing_nullable=False)
        batch_op.create_foreign_key('fk_conversations_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_users', type_='foreignkey')
        batch_op.alter_column('user_id',
                existing_type=fastapi_users_db_sqlalchemy.generics.GUID(),
                type_=sa.VARCHAR(),
                existing_nullable=False)
    
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###